# -*- coding: utf-8 -*-
"""CSE422_lab1_Task2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ekp83DSHF4STwQi5_Qdg9WnlcUbet5QR
"""

# TASK-2:

file = open('E:\\BRAC Study\\CSE422\\Lab1\\input2.txt')

fdata = file.read()

file2 = open('E:\\BRAC Study\\CSE422\\Lab1\\output2.txt', 'w')

data = fdata.split('\n')

row = int(data[0])

data.pop(0)

col = int(data[0])

data.pop(0)

data_matrix = []

queue = []

human = 0

for i in range(row):
   data_matrix.append([])

   data[i] = data[i].replace(" ", "")

   for j in data[i]:

       if j == 'A':
           data_matrix[i].append(0)

           queue.append([i, data[i].index(j)])

       if j == 'H':
           data_matrix[i].append(1)
           human = human + 1

       if j == 'T':
           data_matrix[i].append(2)

time = 0

while True:

   time = time + 1
   queue1 = queue.copy()
   queue.clear()

   for k in queue1:
       b, a = k[0], k[1]

       if b - 1 >= 0 and data_matrix[b - 1][a] == 1:
           data_matrix[b - 1][a] = 0
           human -= 1
           queue.append([b - 1, a])

       if b + 1 < row and data_matrix[b + 1][a] == 1:
           data_matrix[b + 1][a] = 0
           human -= 1
           queue.append([b + 1, a])

       if a - 1 >= 0 and data_matrix[b][a - 1] == 1:
           data_matrix[b][a - 1] = 0
           human -= 1
           queue.append([b, a - 1])

       if a + 1 < col and data_matrix[b][a + 1] == 1:
           data_matrix[b][a + 1] = 0
           human -= 1
           queue.append([b, a + 1])

   if len(queue) == 0:
       time -= 1
       break

print("Time:", time, "minutes")
if human == 0:
   print("No one survived")
   file2.write('Time: ' + str(time) + 'minutes\n' + 'No one survived')

else:
   print(human, "survived")
   file2.write('Time: ' + str(time) + ' minutes\n' + str(human) + ' survived')

